services:
  app:
    container_name: eshop-payment-api
    build: .
    profiles: ["app"]
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - eshop-payment-api-network

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${DATABASE_POSTGRES_NAME}
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
    ports:
      - '5440:5432'
    networks:
      - eshop-payment-api-network

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - '5680:5672'
    networks:
      - eshop-payment-api-network

networks:
  eshop-payment-api-network:
    name: eshop-payment-api-network
