services:
  postgres:
    image: "postgres:15.0-alpine"
    environment:
      - "POSTGRES_DB=payments_db"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=123456"
    ports:
      - "5440:5432"
    networks:
      - eshop-payment-api-network

  rabbitmq:
    image: "rabbitmq:latest"
    environment:
      - "RABBITMQ_DEFAULT_USER=root"
      - "RABBITMQ_DEFAULT_PASS=123456"
    ports:
      - "5680:5672"
    networks:
      - eshop-payment-api-network

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8443:8080
    command:
      - start-dev
    networks:
      - eshop-payment-api-network

  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

networks:
  eshop-payment-api-network:
    name: eshop-payment-api-network
