server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
#  flyway:
#    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
#    user: ${postgres.username}
#    password: ${postgres.password}
#    locations: sql
