h2:
  url: jdbc:h2:mem:payments_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    url: ${h2.url}
  datasource:
    url: ${h2.url}
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
