server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

postgres:
  username: root
  password: 123456
  database: payments_db
  host: localhost
  port: 5440
