spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

postgres:
  url: ${DATABASE_POSTGRES_URL}
  username: ${DATABASE_POSTGRES_USERNAME}
  password: ${DATABASE_POSTGRES_PASSWORD}
  database: ${DATABASE_POSTGRES_NAME}
