server:
  port: 8080

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    tryItOutEnabled: true
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    filter: true

spring:
  flyway:
    enabled: true
    locations: filesystem:src/main/resources/db/migration
    validate-on-migrate: true
    baseline-description: true
    baseline-on-migrate: true
    create-schemas: true
    default-schema: public
    schemas: public
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver

openapi:
  dev-url: http://localhost:8080
  prod-url: http://localhost:8080
