name: Publish images to docker hub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t deyvisonborges/eshop-payments-api:latest
      - name: publish
        run: |
          docker login -u deyvisonborges -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push deyvisonborges/eshop-payments-api:latest
